# Generated by Django 5.2.7 on 2025-11-08 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(default='Guest', max_length=100)),
                ('email', models.EmailField(default='guest@example.com', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('room_type', models.CharField(default='Standard Room', max_length=100)),
                ('check_in', models.DateField(default=django.utils.timezone.now)),
                ('check_out', models.DateField(default=django.utils.timezone.now)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('source', models.CharField(default='Website', max_length=50)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('guest_notes', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(default='Unassigned', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(default='Guest', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('room_type', models.CharField(default='Standard Room', max_length=100)),
                ('check_in', models.DateField(default=django.utils.timezone.now)),
                ('check_out', models.DateField(default=django.utils.timezone.now)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('booking_type', models.CharField(default='Walk-in', max_length=20)),
                ('created_by', models.CharField(default='Admin', max_length=100)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('id_verified', models.BooleanField(default=False)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('special_requests', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('last_cleaned', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Task', max_length=150)),
                ('description', models.TextField(default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.CharField(default='Employee', max_length=100)),
                ('role', models.CharField(default='Staff', max_length=50)),
                ('type', models.CharField(default='General', max_length=50)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('progress', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Video', max_length=200)),
                ('category', models.CharField(default='General', max_length=100)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(default='Employee', max_length=100)),
                ('role', models.CharField(default='Staff', max_length=50)),
                ('department', models.CharField(default='General', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('shift', models.CharField(default='Day Shift', max_length=50)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(default='Guest', max_length=100)),
                ('email', models.EmailField(default='guest@example.com', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('room_type', models.CharField(default='Standard Room', max_length=100)),
                ('check_in', models.DateField(default=django.utils.timezone.now)),
                ('check_out', models.DateField(default=django.utils.timezone.now)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked-in', 'Checked-in'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hotel.room')),
            ],
        ),
    ]
