# Generated by Django 5.2.5 on 2025-11-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
