# Generated by Django 5.2.5 on 2025-11-11 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='check_out',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='offlinebooking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='offlinebooking',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='offlinebooking',
            name='check_out',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
